master:
  installPlugins:
    - ace-editor:1.1
    - apache-httpcomponents-client-4-api:4.5.10-2.0
    - authentication-tokens:1.4
    - bouncycastle-api:2.18
    - branch-api:2.5.8
    - cloudbees-folder:6.14
    - command-launcher:1.4
    - configuration-as-code:1.42
    - credentials:2.3.12
    - credentials-binding:1.23
    - display-url-api:2.3.3
    - durable-task:1.34
    - git:4.3.0
    - git-client:3.3.1
    - git-server:1.9
    - handlebars:1.1.1
    - jackson2-api:2.11.1
    - jdk-tool:1.4
    - jquery-detached:1.2.1
    - jsch:0.1.55.2
    - junit:1.29
    - kubernetes:1.26.4
    - kubernetes-client-api:4.9.2-2
    - kubernetes-credentials:0.7.0
    - lockable-resources:2.8
    - mailer:1.32
    - matrix-project:1.17
    - momentjs:1.1.1
    - pipeline-build-step:2.12
    - pipeline-graph-analysis:1.10
    - pipeline-input-step:2.11
    - pipeline-milestone-step:1.3.1
    - pipeline-model-api:1.7.1
    - pipeline-model-definition:1.7.1
    - pipeline-model-extensions:1.7.1
    - pipeline-rest-api:2.13
    - pipeline-stage-step:2.5
    - pipeline-stage-tags-metadata:1.7.1
    - pipeline-stage-view:2.13
    - plain-credentials:1.7
    - scm-api:2.6.3
    - script-security:1.74
    - snakeyaml-api:1.26.4
    - ssh-credentials:1.18.1
    - structs:1.20
    - trilead-api:1.0.8
    - variant:1.3
    - workflow-aggregator:2.6
    - workflow-api:2.40
    - workflow-basic-steps:2.20
    - workflow-cps:2.81
    - workflow-cps-global-lib:2.17
    - workflow-durable-task-step:2.35
    - workflow-job:2.39
    - workflow-multibranch:2.21
    - workflow-scm-step:2.11
    - workflow-step-api:2.22
    - workflow-support:3.5
